import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
import Hero from "@/components/Hero";
import Nav from "@/components/Nav";
import WhoWeAre from "@/components/WhoWeAre";
import Offerings from "@/components/Offerings";
import FAQ from "@/components/FAQ";
import Sponsors from "@/components/Sponsors";
import Waitlist from "@/components/Waitlist";
import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen ">
        {/* <Nav /> */}
        <Hero />
        <WhoWeAre />
        <Offerings />
        <FAQ />
        <Sponsors />
        <Waitlist />
        {/* <Footer /> */}
      </main>
    </>
  );
}
